### ISSUE TITLE
Using picfit as a "function"

### ISSUE THREAD

**Issue by douglasmiranda** [thoas/picfit#108]
I want to use picfit as a function or as a simple webservice that will receive a image(url), crop it and output my thumbnail in the `display/` endpoint. (then my app will download and do other things with the image)

Just by using an empty config.json `{}`

And something like:
http://localhost:3001/display?url=http://domain/image.jpg&op=thumbnail&w=250&h=200

I'm kinda getting the desired behavior, I just don't know if it the application is designed to achieve something like this.

**Comment by douglasmiranda** [comment]
Well, it looks like I found what I was looking for:

- https://github.com/DarthSim/imgproxy

**Comment by theromis** [comment]
I'm already using it as function, just moved out into my "utils" code for "thumbnail generation".

**Comment by theromis** [comment]
@douglasmiranda please check https://github.com/thoas/picfit/pull/117
