### ISSUE TITLE
Panic: runtime error: index out of range in parser middleware

### ISSUE THREAD

**Issue by malyusha** [thoas/picfit#109]
Hello!
Found a bug - server panics when `url` is incorrect format, (e.g. `/display/sig/resize/100x100`) here: https://github.com/thoas/picfit/blob/master/middleware/parsers.go#L33

I guess, you should check if index of sub regexp name exists inside slice of regexp matches, because in that case their lengths are not equal.

**Comment by thoas** [comment]
will be solved with #114
