### ISSUE TITLE
Wrong signature generation

### ISSUE THREAD

**Issue by beannt** [thoas/picfit#129]
The command line signature test produce difference signature and url.  The url always return invalid signature.

` ./picfit signature --key=abcdef "w=100&h=100&op=resize"
Query String: w=100&h=100&op=resize
Signature: 954eec9dfa9390f8f4264e15bb95f5f54e6fe953
Signed Query String: w=100&h=100&op=resize&sig=6f7a667559990dee9c30fb459b88c23776fad25e
`

**Comment by ornicar** [comment]
You need to give the query parameters in alphabetical order for the signature to work.

**Comment by thoas** [comment]
It's not mentioned in the `README`, thank you for the answer @ornicar.
