### ISSUE TITLE
prop:Help

### ISSUE THREAD

**Issue by remotejob** [thoas/picfit#133]
1. In case if storage fs
how get **original** image without any Operation?

"storage": {
        "src": {
            "type": "fs",
            "location": "/root/images"
        }
    },

2. How correctly use Method GET?
http http://142.93.177.207:3001/get&path=/root/images/display.jpeg 
http http://142.93.177.207:3001/get&filename=display.jpeg
Request should contains parameters or query string ?

**Comment by thoas** [comment]
You can use the `noop` operation parameter directly, it will return the original image.
