### ISSUE TITLE
Dockerfile Build fails to compile on M1 mac

### ISSUE THREAD

**Issue by thenetimp** [thoas/picfit#141]
Trying to generate a docker container on my M1 Macbook spits out this error.

`#11 0.945 fatal: not a git repository (or any of the parent directories): .git
#11 0.946 fatal: not a git repository (or any of the parent directories): .git
#11 1.476 -> Creating statically linked binary...
#11 1.478 mkdir -p /go/src/github.com/thoas/picfit/bin
#11 1.489 go build -mod=vendor -ldflags "\
#11 1.489       -X github.com/thoas/picfit/constants.Branch= \
#11 1.489       -X github.com/thoas/picfit/constants.Revision= \
#11 1.489       -X 'github.com/thoas/picfit/constants.BuildTime=2021-02-18 18:36:19 UTC+0000' \
#11 1.489       -X 'github.com/thoas/picfit/constants.Compiler=go version go1.15.8 linux/arm64'" -a -installsuffix cgo -o /go/src/github.com/thoas/picfit/bin/picfit ./cmd/picfit/main.go
#11 10.58 # github.com/discordapp/lilliput
#11 10.58 gcc: error: unrecognized command line option '-msse'; did you mean '-fdse'?
#11 10.58 gcc: error: unrecognized command line option '-msse2'
#11 10.58 gcc: error: unrecognized command line option '-msse3'
#11 10.58 gcc: error: unrecognized command line option '-msse4.1'
#11 10.58 gcc: error: unrecognized command line option '-msse4.2'
#11 10.58 gcc: error: unrecognized command line option '-mavx'
#11 10.58 gcc: error: unrecognized command line option '-msse'; did you mean '-fdse'?
#11 10.58 gcc: error: unrecognized command line option '-msse2'
#11 10.58 gcc: error: unrecognized command line option '-msse3'
#11 10.58 gcc: error: unrecognized command line option '-msse4.1'
#11 10.58 gcc: error: unrecognized command line option '-msse4.2'
#11 10.58 gcc: error: unrecognized command line option '-mavx'
#11 10.58 gcc: error: unrecognized command line option '-msse'; did you mean '-fdse'?
#11 10.58 gcc: error: unrecognized command line option '-msse2'
#11 10.58 gcc: error: unrecognized command line option '-msse3'
#11 10.58 gcc: error: unrecognized command line option '-msse4.1'
#11 10.58 gcc: error: unrecognized command line option '-msse4.2'
#11 10.58 gcc: error: unrecognized command line option '-mavx'
#11 11.50 make: *** [Makefile:51: build-static] Error 2
------
executor failed running [/bin/sh -c make docker-build-static && mv bin/picfit /picfit]: exit code: 2
jandrews@Matrix picfit % code .`

**Comment by thoas** [comment]
use Docker for this, `lilliput` does not support arm64.
