### ISSUE TITLE
Minio (and others) s3 storage support

### ISSUE THREAD

**Issue by mamchyts** [thoas/picfit#149]
Hi, 
Do you have any plans for support different S3 storages?
We use docker (k8s). As a result we use Minio S3 storage.
Your solution can works only with vendor lock S3.
Also looks like you can add optional parameter - **s3_endpoint**, as result we can configure it with next value:  **s3_endpoint=http://minio:9000**. 

What do you think?

**Comment by thoas** [comment]
@mamchyts yes, you can send me a PR and I will review it.
