### ISSUE TITLE
'make build' fails on mac

### ISSUE THREAD

**Issue by sacheu** [thoas/picfit#19]
Hi,

I am trying to run picfit on Mac.  I have setup $GOPATH correctly and use homebrew to install go on my  MAC.

This is the error I got:

$ echo $GOPATH
/Users/MIKE/gocode

$ make build                                                              
-> Compiling picfit binary
main.go:6:2: cannot find package "github.com/thoas/picfit/application" in any of:
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/github.com/thoas/picfit/application (from $GOROOT)
    /Users/MIKE/Src/picfit/Godeps/_workspace/src/github.com/thoas/picfit/application (from $GOPATH)
    /Users/MIKE/gocode/src/github.com/thoas/picfit/application
main.go:7:2: cannot find package "github.com/thoas/picfit/signature" in any of:
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/github.com/thoas/picfit/signature (from $GOROOT)
    /Users/MIKE/Src/picfit/Godeps/_workspace/src/github.com/thoas/picfit/signature (from $GOPATH)
    /Users/MIKE/gocode/src/github.com/thoas/picfit/signature
godep: go exit status 1
make: *** [build] Error 1

**Comment by thoas** [comment]
You need to checkout this repository in you src directory.

For example mine:

```
[git:master] thoas belgariade ~/Sites/golang/src/github.com/thoas/picfit
$ pwd
/Users/thoas/Sites/golang/src/github.com/thoas/picfit
[git:master] thoas belgariade ~/Sites/golang/src/github.com/thoas/picfit
$ echo $GOPATH
/Users/thoas/Sites/golang
```
