### ISSUE TITLE
Author Master, PNG to JPEG cannot control the background color, which makes it very ugly. I hope to deal with it ﻿

### ISSUE THREAD

**Issue by huddhudd** [thoas/picfit#191]
![image](https://github.com/thoas/picfit/assets/8034908/d20b425b-b175-41b1-86ea-df84686d34e6)

https://data.yunqidong.com:8877/up/10/10/333903/65f41d9fbdab7476342208.png?w=86&q=50&fmt=jpeg&c=ffffff

**Comment by huddhudd** [comment]
Author Master, PNG cannot control the background color, which makes it very ugly. I hope to deal with it

**Comment by thoas** [comment]
Happy to review a PR to fix this issue :)
