### ISSUE TITLE
The latest docker image on docker hub thoas/picfit:0.14.0 only supports arm64

### ISSUE THREAD

**Issue by Carbrex** [thoas/picfit#192]
Please make it support amd64 architecture also?
https://hub.docker.com/layers/thoas/picfit/0.14.0/images/sha256-cf6a67224e3abea0ad0d8d0bf27b88a5a4dcb4de2ec89386721727515d2aa444?context=explore

**Comment by Carbrex** [comment]
Also, here's a dockerfile for alpine image if you plan on adding it
```
# Build stage
FROM golang:1.22.1-alpine3.19 AS build

RUN apk --no-cache add git make

WORKDIR /opt

RUN git clone --depth 1 https://github.com/thoas/picfit.git
RUN make -C /opt/picfit build

# Runtime stage
FROM alpine:3.19

COPY --from=build /opt/picfit/bin/picfit /picfit

ENTRYPOINT ["/picfit"]
```

**Comment by thoas** [comment]
fixed @Carbrex 

thank you, didn't know you have to provide the `--platform linux/amd64` now.
