### ISSUE TITLE
Using picfit via Proxy for Amazon S3

### ISSUE THREAD

**Issue by Nasfy** [thoas/picfit#194]
Hello,

I would like to inquire if picfit supports the ability to load images from Amazon S3 via a proxy, instead of directly accessing S3. Currently, we are using an Nginx proxy server to access S3, and we are interested in using picfit for image processing on images pre-uploaded to S3.

If picfit supports such functionality, please specify what settings or configurations are required to achieve this. We are keen on leveraging picfit via a proxy for image processing in our project.

Thank you!

**Comment by thoas** [comment]
You are looking for the `http+s3` storage type, see the documentation for more information.
