### ISSUE TITLE
restrict available resize configurations

### ISSUE THREAD

**Issue by sharpner** [thoas/picfit#20]
I am currently using this project https://github.com/VoycerAG/gridfs-image-server which allows me to restrict resize sizes for images.

Otherwise an attacker could resize images to high resolutions and reduce my available cpu.

**Comment by thoas** [comment]
You can configure Security with a secret key that only you know.

Parameters are encoded with your secret key and picfit will match the provided key and your parameters.

See [here](https://github.com/thoas/picfit#security)

**Comment by EvanPurkhiser** [comment]
It would still be nice to see this feature.

Signing is good, but when used with an edge cache it means replacing the signing key causes all cached objects to no longer be valid at the edge, which is no good. You can move the signing to the edge cache (such as with cloudfront) in which case the edge cache will understand that when the key changes not to invalidate the cache. You can also maybe configure your edge cache to understand the signature segment of the URL and not key on that.

But all of this difficulty for when you simply need to restrict what sizes are allowed seems overly complicated in lieu of a configuration for the sizes.

Would you be willing to accept a PR?
