### ISSUE TITLE
Don't support AWS Signature V4 API

### ISSUE THREAD

**Issue by gavin-k** [thoas/picfit#31]
Hi thoas,
    Today,I use your <code>picfit</code> on my server with S3.
    But <code>picfit</code> report <code>Please use AWS4-HMAC-SHA256</code>.
    To solve this problem , what can I do ?

**Comment by thoas** [comment]
Hello,

Could you provide me more information? A stacktrace? Logs output?

Thank you :)

**Comment by gavin-k** [comment]
OK. Of course.
Here is my <code>config.json</code>
![c3cgq k tc3qygyv9mkk en](https://cloud.githubusercontent.com/assets/7688199/10714698/6c15c04e-7b35-11e5-857d-5b0e11489aff.png)

Here is the <code>picfit</code> output error.
![oo6y xeya n8 j8v e_v6p](https://cloud.githubusercontent.com/assets/7688199/10714707/944279fe-7b35-11e5-83e7-b69a78a361b9.png)

Thank you :)

**Comment by thoas** [comment]
Ok, sorry for the delay.

It seems the [goamz](https://github.com/mitchellh/goamz) library we are using does not support the v4 signature, the solution could be using the official one from amazon but I need some time to migrate [gostorages](https://github.com/thoas/gostorages)

**Comment by gavin-k** [comment]
Ok,Thank you,Sir.
You are very kind.
