### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by alexd6631** [thoas/picfit#33]
Hello, 

After a few day of use, I encounter "too many open files" issues.

Here is a log of these errors :

time="2015-12-01T10:04:16+01:00" level="info" msg="PANIC: open /home/www/picfit/storage/c53a33374205508dda23b27f6f0a6b5e.jpg: too many open files\ngoroutine 28338 [running]:\ngithub.com/thoas/picfit/middleware.func·001()\n\t/home/www/gowork/src/github.com/thoas/picfit/middleware/middleware.go:36 +0x12b\nruntime.panic(0x864120, 0xc208ffb170)\n\t/usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d\ngithub.com/thoas/picfit/application.func·001(0x7f047d09c338, 0xc209134380, 0xc20d20d860, 0xc20803e120)\n\t/home/www/gowork/src/github.com/thoas/picfit/application/handlers.go:22 +0xaf\ngithub.com/thoas/picfit/application.func·017(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/thoas/picfit/application/application.go:122 +0x2d1\nnet/http.HandlerFunc.ServeHTTP(0xc2080bf6c0, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/usr/lib/go/src/pkg/net/http/server.go:1235 +0x40\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc208019130, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/gorilla/mux/mux.go:98 +0x292\ngithub.com/codegangsta/negroni.func·001(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc209197ac0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:41 +0x56\ngithub.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc2080f3ba0, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc209197ac0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a\ngithub.com/codegangsta/negroni.middleware.ServeHTTP(0x7f047d09aed0, 0xc2080f3ba0, 0xc2080e5460, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c\ngithub.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x56\ngithub.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc2080e5320, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc2091978e0)\n\t/home/www/gowork/src/github.com/meatballhat/negroni-logrus/middleware.go:42 +0x349\ngithub.com/codegangsta/negroni.middleware.ServeHTTP(0x7f047d09af20, 0xc2080e5320, 0xc2080e5440, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c\ngithub.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x56\ngithub.com/rs/cors.(*Cors).ServeHTTP(0xc20803f950, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc2091978c0)\n\t/home/www/gowork/src/github.com/rs/cors/cors.go:188 +0x155\ngithub.com/codegangsta/negroni.middleware.ServeHTTP(0x7f047d09aef8, 0xc20803f950, 0xc2080e5420, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c\ngithub.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x56\ngithub.com/thoas/picfit/middleware.(*Logger).ServeHTTP(0xc20802a398, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc209197620)\n\t/home/www/gowork/src/github.com/thoas/picfit/middleware/middleware.go:63 +0x18c\ngithub.com/codegangsta/negroni.middleware.ServeHTTP(0x7f047d09aea8, 0xc20802a398, 0xc2080e5400, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c\ngithub.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x56\ngithub.com/thoas/picfit/middleware.(*Recovery).ServeHTTP(0xc2080e51e0, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0, 0xc209197600)\n\t/home/www/gowork/src/github.com/thoas/picfit/middleware/middleware.go:56 +0x9b\ngithub.com/codegangsta/negroni.middleware.ServeHTTP(0x7f047d09ae80, 0xc2080e51e0, 0xc2080e53e0, 0x7f047d09c338, 0xc209134380, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c\ngithub.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc2080adf80, 0x7f047d09c2a0, 0xc2084a5b80, 0xc20a4c1ba0)\n\t/home/www/gowork/src/github.com/codegangsta/negroni/negroni.go:73 +0x10a\nnet/http.serverHandler.ServeHTTP(0xc2080fc420, 0x7f047d09c2a0, 0xc2084a5b80, 0xc20a4c1ba0)\n\t/usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f\nnet/http.(*conn).serve(0xc20d42cd80)\n\t/usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e\ncreated by net/http.(*Server).Serve\n\t/usr/lib/go/src/pkg/net/http/server.go:1721 +0x313\n"
2015/12/01 10:05:25 http: Accept error: accept tcp [::]:3001: too many open files; retrying in 5ms

**Comment by alexd6631** [comment]
Here is my configuration :

```
{
  "port": 3001,
  "storage": {
    "src": {
      "type": "fs",
      "location": "/home/www/picfit/storage"
    }
  },
  "kvstore": {
    "type": "cache"
  }
}
```

Here is my picfit version :

```
./picfit --version
picfit version 0.2

Running on Debian 8 64bits.

**Comment by thoas** [comment]
Will investigate on this point.

Thank you for the report

**Comment by thoas** [comment]
could you run ``sudo lsof -p $(ps axf | grep picfit | grep -v grep | awk '{print  $1}')`` and give me the output?

**Comment by alexd6631** [comment]
[picfit_lsof.txt](https://github.com/thoas/picfit/files/52793/picfit_lsof.txt)

Hello,

Here is attached the result of lsof.
Note the problem is not happening yet (have to wait a few more days of usage), but I can observe a lot of sockets remaining in CLOSE_WAIT state.

**Comment by sontags** [comment]
Same problem here. It's picfit behind a nginx: 

picfit Config:

``` json
{
  "port": 3001,
  "debug": true,
  "storage": {
    "src": {
      "type": "http+fs",
      "base_url": "http://static.stxt.media.int",
      "location": "/data/picfit"
    }
  }
}
```

``` ini
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;

        root /data/nginx;

        location / {
            autoindex on;
        }

        location ~ ^/picfit/.* {
            proxy_pass http://static.int:3001;
            rewrite ^/picfit/(.*) /$1 break;
            proxy_set_header Host $host;
	    proxy_send_timeout 10s;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
```

Also the same symptoms are visible: A new connection is opened for every request. Almost every connection remains in `CLOSE_WAIT` and never gets deleted...

**Comment by thoas** [comment]
hmm... could you send me also the lsof output?

I'm still investigating, it seems only concerned the fs storage as I'm using the s3 storage and not having the issue.

**Comment by sontags** [comment]
[lsof.txt](https://github.com/thoas/picfit/files/108029/lsof.txt)

There you go...

**Comment by sontags** [comment]
Updated the config in order to cache the image hashes:

```
{
  "port": 3001,
  "storage": {
    "src": {
      "type": "http+fs",
      "base_url": "http://static.stxt.media.int",
      "location": "/data/picfit/"
    },
    "dst": {
      "type": "fs",
      "location": "/data/picfit/"
    }
  },
  "kvstore": {
    "type": "cache"
  }
}
```

Now, only requests that needs to be processed/generated remain in `CLOSE_WAIT`

Hope that helps

**Comment by thoas** [comment]
Ok guys, sorry for the delay really busy at the moment. I will take a moment to review the problem this week, if you do find the problem before me don't hesitate to send me a PR.

**Comment by sontags** [comment]
No worries, having the `kvstore` in place is a pretty ok workaround for me since most requests go for the same stuff... I'll have a look at it if I find some time...

**Comment by alexd6631** [comment]
I suspect the leak happens every time a URL is fetch using :  https://github.com/thoas/picfit/blob/master/http/http.go#L41

As mentioned, in this goreq discussion : https://github.com/franela/goreq/issues/76, a call to `resp.Body.Close()` is required to prevent CLOSE_WAIT socket leak, and it seems ioutil.ReadAll wont perform the close by itself.

Although my experience in go is limited I would suggest adding a defer statement to ensure the request is closed on every function return.

```
content, err := goreq.Request{Uri: u.String()}.Do()
if err != nil {
	return nil, err
}
defer content.Body.Close()
```

I will run some test this week, to see if it fixes the leak.

**Comment by alexd6631** [comment]
I can confirm that adding the following line to : 

```
defer content.Body.Close()
``` 

to both `OpenFromURL` and `HeadersFromURL` fixes the CLOSED_WAIT leak.

**Comment by thoas** [comment]
Thank you @alexd6631 I take some time to add the closing :)
