### ISSUE TITLE
Mimetype check fails if no extension in URL

### ISSUE THREAD

**Issue by steevee** [thoas/picfit#37]
### Problem

If trying to resize a URL that doesn't specify an image file extension,  Picfit logs the error:

```
Mimetype  is not supported
```

(note: there is a blank mimetype in there!)

If I remove [these lines in application/extractors.go](https://github.com/thoas/picfit/blob/a767439b914b7bed3ed0fd54c5ff9edd390805fd/application/extractors.go#L39-L43) it will work.

I can't find anything that says images must have an extensions of a valid mime-type for a browser to render them, so perhaps this check is not needed? The downside is we could waste an invalid request.

Perhaps also post fetching the request, checking the `Content-Type` would be a more accurate method for detecting the mimetype, but even then it's not always reliable and we could _try our luck_ with the binary we've already downloaded and see if the binary is recognised as an image.
### Use cases

I'm trying to use some 3rd party URLs - that out of my control - such as G+ content: 
https://lh3.googleusercontent.com/-EK0G4CdvOUk/VmWSzy2Mc2I/AAAAAAACD3o/Czlh2uHi3To/w530-h353-p-rw

NOTE: googleusercontent.com does actually allow for filenames to be appended to it's urls. 
e.g. https://lh3.googleusercontent.com/-EK0G4CdvOUk/VmWSzy2Mc2I/AAAAAAACD3o/Czlh2uHi3To/w530-h353-p-rw/surprise.jpg
However, I expect and have tested others that do not allow this.

**Comment by thoas** [comment]
Already aware of this issue, it should be fixed by downloading the image and reading the mimetype.

**Comment by steevee** [comment]
What do you think the behaviour should be if there is neither an extension nor a "Content-Type" header to determine the mimetype?

**Comment by steevee** [comment]
@thoas sorry, my mistake, of course the image doesn't work without a mime-type, rather the `Application.DefaultFormat` is used (`png`).

I removed the initial check and changed `ImageFile.ContentType` logic to use the `Content-Type` header before failing over to `mime.TypeByExtension`.

Pull request imminent.
