### ISSUE TITLE
ENV variables in config

### ISSUE THREAD

**Issue by omarvelous** [thoas/picfit#45]
Greetings,

I was wondering if you'd welcome the addition of support for ENV varibales in config? We found it helpful from a docker image perspective to extract some config variables to ENV variables we set on the fly. This allowed us to use the same image regardless of configuration. Is this a feature you think we should submit a PR for?

The other idea we had was to allow te passing of config inline, which might be even better than the ENV variables support.

Let us know!

Thanks,

O

**Comment by thoas** [comment]
I do use Docker in production, you just need to mount a volume with your config file in it.

``docker run thoas/picfit:0.3.0 -v /etc/picfit:/etc/picft -e "PICFIT_CONFIG_PATH=/etc/picfit/config.json"``

**Comment by omarvelous** [comment]
True. Curious, how do you handle the maintenance of the config files? We definitely thought about this path (pun intended).

**Comment by thoas** [comment]
I'm deploying a config file on disk with Ansible, reload docker. You can definitely use a versioning tag for your config file

**Comment by omarvelous** [comment]
Very interesting... I like it...

**Comment by kennethkalmer** [comment]
What if you're deploying picfit to something like Kubernetes (or any other clustered setup), where managing and mounting config file as a volume isn't practical.

Could the config not be parsed with `template/text` and a helper (or two) for reading values from ENV first?
