### ISSUE TITLE
Docker Tag 0.3.0 not found

### ISSUE THREAD

**Issue by MathieuDoyon** [thoas/picfit#47]
docker image seems to be outdated

Unable to find image 'thoas/picfit:0.3.0' locally
Pulling repository docker.io/thoas/picfit
Tag 0.3.0 not found in repository docker.io/thoas/picfit

**Comment by thoas** [comment]
it's ``thoas/picfit:0.3`` and you are right it should be ``thoas/picfit:0.3.0``

[see](https://hub.docker.com/r/thoas/picfit/tags/)
