### ISSUE TITLE
Signature helper command does not sort or encode query string

### ISSUE THREAD

**Issue by EvanPurkhiser** [thoas/picfit#52]
It would be nice if the `picfit signature` helper command would sort the query string for you.

It may also be nice if it also encoded the query string.

Basically, the command should do something [similar to this](https://github.com/thoas/picfit/blob/a767439b914b7bed3ed0fd54c5ff9edd390805fd/application/request.go#L93-L98).

At the very least, it would probably be worthwhile to mention in the documentation that the query string is sorted and encoded when doing the signature verification.

**Comment by thoas** [comment]
thank you for the report
