### ISSUE TITLE
Use AWS_ACCESS_KEY from env?

### ISSUE THREAD

**Issue by bpicolo** [thoas/picfit#53]
Looks like this is supported by the storage backend, but it seems picfit only takes the JSON params. Is it currently possible to use AWS_ACCESS_KEY/SECRET from env or ~/.aws/credentials?

If so, what's the right way to configure it?

**Comment by austenito** [comment]
👍  for this. It would actually be great to have a bunch of things configurable via environmental variables. For my use case specifically, I would like to deploy picfit to Heroku.

Would using something like https://github.com/spf13/viper work where we could use either environmental variables and a `config.json` work?

**Comment by thoas** [comment]
I'm currently refactoring the ``config.json`` thing with viper, so stay tuned

**Comment by austenito** [comment]
Great to hear it! Thanks for all your work! 🎉
