### ISSUE TITLE
Defaults not preserved correctly

### ISSUE THREAD

**Issue by EvanPurkhiser** [thoas/picfit#60]
Because of the way defaults are not deeply set, if you reconfigure a deep option, for example, enabling `options.enable_upload`, then all defaults in the `options` block will not correctly be defaulted. This is very noticeable for the `options` key since quality is set to 0 and looks very bad.

This is due to setting the default for the top level keys to a default struct, and then allowing the struct to be replaced when a single deep option is set.

**Comment by thoas** [comment]
Ok thks for the reporting, I think this is the way viper set the default for a whole struct.

**Comment by thoas** [comment]
should be fixed in master, I will add some tests tomorrow.

Thank you for the report

**Comment by EvanPurkhiser** [comment]
You rock man! 👍
