### ISSUE TITLE
How can I customize the http request header when requesting for external image?

### ISSUE THREAD

**Issue by beeant** [thoas/picfit#64]
Some external image restrict their response to only browser user-agent. For example,
http://localhost:8080/display?op=resize&url=http://i-give-you.pics/only/if/you/use/browser.jpg
this request will give you no image, with non-custom user-agent.

**Comment by thoas** [comment]
Hi,

You can't customize the header when requesting for an external image, I'm accepting PRs if you want to provide this feature in the config :)

Nice idea btw.
