### ISSUE TITLE
How to custom upload directory?

### ISSUE THREAD

**Issue by rinetd** [thoas/picfit#67]
I do not want to put the upload and cache files in the same directory

**Comment by thoas** [comment]
if you do not specify the destination storage then the source storage will be used.

**Comment by nd2s** [comment]
@thoas Isn't it possible to set a directory in the upload request? I need to upload to individual "buckets", like: `a/img1.jpg`, `a/img2.jpg`, `b/img1.jpg`. Then I could get images using this paths, and cache files are stored normally in the root dir. 

I can't find any option in the upload route for this?
