### ISSUE TITLE
Configuration file: use TOML instead of JSON

### ISSUE THREAD

**Issue by keltia** [thoas/picfit#82]
JSON is not an ideal configuration file (no comment allowed for example), I'd suggest using TOML instead.

It is more readable/editable and is as easy to serialize/deserialze.  There are several Go packages for that including `github.com/naoina/toml` and `github.com/BurntSushi/toml`.

**Comment by thoas** [comment]
It’s a matter of choice and preference, not a big fan of toml.

**Comment by thoas** [comment]
You are free to add support for toml if you want, I don’t want to waste my time for it this project has more needs.
