### ISSUE TITLE
Whether to provide more detailed installation documentation?

### ISSUE THREAD

**Issue by kslr** [thoas/picfit#84]
Hello, non-Golang user installation is really confusing

I can not find package in ~ make build
I switched to ~/go/src but clone still fails after compilation

**Comment by kslr** [comment]
OK, I found a document and it succeeded
http://www.nikola-breznjak.com/blog/miscellaneou/self-hosted-image-upload-resize-script-go/

**Comment by thoas** [comment]
nice, I will detail it in a blog post, actually if you have docker installed you can launch `make docker-build` without installing Go.

You are right, it needs a better tutorial :)
