### ISSUE TITLE
undefined syscall.Stat_t

### ISSUE THREAD

**Issue by tobya** [thoas/picfit#85]
I would like to try to compile for windows if possible. 

I did a git clone on repo then

    go build 

I got the following error

  >undefined syscall.Stat_t

Is there a simple solution to this issue?

**Comment by steevee** [comment]
Hi @tobya,

Can you confirm the error is coming from the vendor dep `github.com/thoas/gostorages/fs.go`?

If so, `github.com/thoas/gostorages` no longer exists, but was forked from `github.com/ulule/gostorages` - which no longer seems to rely on the architecture specific `syscall.Stat_t`. 

You could try updating the go dep to use `github.com/ulule/gostorages`, see if it works, and if it does, submit a PR.

**Comment by thoas** [comment]
@tobya I have update the dependencies to the latest version of `ulule/gostorages` it should resolve your issue.

Let us know :)

@steevee thks for the support btw!

**Comment by tobya** [comment]
Builds on windows now, thanks for the quick response.
