### ISSUE TITLE
Cache misses

### ISSUE THREAD

**Issue by tobya** [thoas/picfit#90]
Hello

Thank you for such a great little utility.

I'm having some issue with caching the results of a image thumbnail and then the image not being recognised as being on disk when requested maybe a day later.

This is my picfit config file

     {
      "port": 28080,
      "storage": {
      "src": {
      "type": "fs",
      "location": "d:\\picfit\\"
      }
     },
      "kvstore" : {
       "type" : "cache"
      },
      "options": {
        "enable_stats": true,
       "enable_delete": true
       }
     }

(I tried including the sharding options but had same issue)

I start it like this 

I get errors like this when I visit a page with multiple thumbnail requests produced by this request

    
 >    img src="https://imgur.azure.ccc.ie/display?url=https://bbb.ccc.ie/studentimages/623706.jpg&w=105&h=105&op=thumbnail" border=0>

There is no possibility these have not been created before as they are on one of our most used pages.

←[36mINFO←[0m[2948] Key b74f659b92b4c5c4483cc2b3a9eca39b not found in kvstore
←[36mINFO←[0m[2954] Save thumbnail b74f659b92b4c5c4483cc2b3a9eca39b.jpg to storage
←[36mINFO←[0m[2954] Save key b74f659b92b4c5c4483cc2b3a9eca39b => b74f659b92b4c5c4483cc2b3a9eca39b.jpg to kvstore
←[36mINFO←[0m[2954] Put key into set d41d8cd98f00b204e9800998ecf8427e:children () => b74f659b92b4c5c4483cc2b3a9eca39b in
 kvstore

I am using Windows Server 2012 with caddy and php 5.6.  Is there anything obvious that would be causign these misses?

**Comment by tobya** [comment]
Unfortunately not fixed.

It seems to miss cache hits particuarily when viewed on a chrome incognito window

**Comment by thoas** [comment]
regarding #41 does this issue still exists?

**Comment by tobya** [comment]
Yes I think it is, I decided it was something to do with Windows.  The cache never seemed to engage.  I moved my usage to https://www.imgix.com/ . Thanks for the repo.
