### ISSUE TITLE
Invalid Mime Type if url does not finish with filename extension

### ISSUE THREAD

**Issue by tobya** [thoas/picfit#91]
Hi

I am trying to retrieve an image for resizing from this url 

> example.com/zp-core/full-image.php?a=2018/12 Week Jan/Week4/Mon 29th Jan 2018&i=2018-01-29 16.32.04.jpg&q=75&wmk=!&dsp=Protected view&check=0e9c970a98d783df6fcd8a834de80ddf097c8eec

I get an error 

> Mimetype  is not supported

I think the code thinks the mimetype is php rather than jpg but i might be wrong?

**Comment by steevee** [comment]
@tobya 

By default picfit uses the file extension to determine the mimetype, but it supports another version, `fastimage` too. Just add it to your config file.

```json
{
  "options": {
    "mimetype_detector": "fastimage"
  }
}
```

n.b. will make two requests for the file now though (albeit, `github.com/rubenfonseca/fastimage` will do a partial fetch)
